project_list/project_list/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

# app_name = "projects"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name="index"),
    path("to_do/", include("to_do.urls"), name="to_do"),
]

project_list/to_do/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "to_do"
urlpatterns = [
    path("",views.index,name='index'),
    path("register/",views.register,name='register'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('login/',LoginView.as_view(template_name='to_do/login.html'),name='login'),
    path('add_task/',views.add_task,name='add_task'),
    path('details/<int:id>/',views.details,name='details'),
    path('edit/<int:id>/',views.edit,name='edit'),
    path('remove/<int:id>/',views.remove,name='remove'),
]

project_list/to_do/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    # user will have one to many realtionship with task
    # .cascaede will delete the task of that user if the user is deleted we can keep the task by using set_null
    user =  models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, default=User.username)

    title = models.CharField(max_length=200, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    status = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['status']

project_list/to_do/forms.py
from .models import Task
from django import forms

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['user', 'title', 'desc', 'status']

project_list/project_list/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'project_list/index.html')

project_list/to_do/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.contrib.auth.forms import UserCreationForm
from .forms import TaskForm

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        todo_list = Task.objects.filter(user=request.user)
        return render(request, 'to_do/index.html', {'todo_list':todo_list})
    return render(request, 'to_do/index.html')

def register(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'to_do/index.html')
    else:
        form = UserCreationForm()
    return render(request, 'to_do/register.html', {'form':form})

def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('to_do:index')
        
    else:
        form = TaskForm()
    return render(request, 'to_do/add_task.html', {'form':form})

def details(request, id):
    task = Task.objects.get(id=id)
    return render(request, 'to_do/details.html', {'to_do':task})

def edit(request,id):
    task=Task.objects.get(id=id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('to_do:index')
        
    else:
        form = TaskForm(instance=task)
    return render(request, 'to_do/edit.html', {'form':form})

def remove(request, id):
    to_be_remove=Task.objects.get(id=id)
    to_be_remove.delete()
    return redirect('to_do:index')

project_list/templates/project_list/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project list</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>

<body>
    <h1 style="text-align: center;">Link of the Projects</h1>
    <table class="table table-striped container">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Content</th>
                <th scope="col">Link</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>To do</td>
                <td><a href="to_do/">Click here</a></td>
            </tr>
        </tbody>
    </table>
</body>

</html>

project_list/to_do/templates/to_do/add_task.html
{% extends 'to_do/base.html' %}

{% block content %}
<div class="my_container">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="bbtn" style="display: inline-block; margin-left: 8vw;">Add task</button>
</form>
</div>
{% endblock %}

project_list/to_do/templates/to_do/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>nav-bar</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'todo/style.css' %}">
</head>

<body>
    <header class="fflex ">
        <a href="{% url 'to_do:index' %}" class="bbrand-logo">Brand logo</a>
        <ul>
            <li><a href="{% url 'to_do:index' %}" class="nnav-link">Home</a></li>
            <li><a href="#" class="nnav-link">About</a></li>
            <li><a href="{% url 'index' %}" class="nnav-link">Project list</a></li>
        </ul>
        <a href="{% url 'to_do:logout' %}"><button class="bbtn">Log out</button></a>
    </header>
    {% block content %}
    {% endblock %}
</body>

</html>

project_list/to_do/templates/to_do/details.html
{% extends 'to_do/base.html' %}

{% block content %}
<h1>Details for {{ to_do.title }}</h1>
<h2>{{to_do.desc}}</h2>
<h3>{{to_do.status}}</h3>
<h4>{{to_do.created}}</h4>
{% endblock %}

project_list/to_do/templates/to_do/edit.html
{% extends 'to_do/base.html' %}
{% load static %}
<html>

<head>
    <link rel="stylesheet" href="{% static 'to_do/style.css' %}">
    <style>
        .my_container{
            border: 2px solid red;
            border-radius: 50px;
        }
    </style>
</head>

<body>
    {% block content %}
    <div class="my_container">
        <form method="POST" style="z-index: 2;">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="bbtn" style="margin-left: 9vw;">Save</button>
        </form>
    </div>
    {% endblock content%}
</body>

</html>

project_list/to_do/templates/to_do/index.html
{% extends 'to_do/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Items</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todo/style.css' %}">
</head>

<body>
    <!-- <h1>askljf</h1> -->
    <!-- nav-bar -->
    {% block content %}
    <div class="container"> 
        <h1 style="text-align: center;">Welcome, {{user.username}}</h1>
        <table class="table table-striped">
            <thead>
              <tr>
                <!-- <th scope="col">#</th> -->
                <th scope="col">Items</th>
                <th scope="col">status</th>
                <th scope="col">Edit</th>
                <th scope="col">Remove Task</th>
              </tr>
            </thead>
            <tbody>
                {% for i in todo_list %}
              <tr>
                <!-- <th scope="row">{{cnt}}</th> -->
                <td>{{i.title}}</td>
                <td>{{i.status}}</td>
                <td><a href="{% url 'to_do:edit' i.id %}">Edit</a></td>
                <td><a href="{% url 'to_do:remove' i.id %}">Remove</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <button class="btn-add-item"><a href="{% url 'to_do:add_task' %}">Add Item</a></button>
    </div>
    {% endblock %}
</body>

</html>

project_list/to_do/templates/to_do/login.html
{% extends 'to_do/base.html' %}


{% block content %}
<div class="my_container">
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="bbtn" style="display: inline-block; margin-left: 5vw;">Log in</button>
</form>
</div>
{% endblock %}

project_list/to_do/templates/to_do/register.html
{% extends 'to_do/base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Register</button>
</form>
{% endblock %}